/*
 * This file is generated by jOOQ.
*/
package test.data.tables.daos;


import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import test.data.tables.ContentItemAction;
import test.data.tables.records.ContentItemActionRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContentItemActionDao extends DAOImpl<ContentItemActionRecord, test.data.tables.pojos.ContentItemAction, UUID> {

    /**
     * Create a new ContentItemActionDao without any configuration
     */
    public ContentItemActionDao() {
        super(ContentItemAction.CONTENT_ITEM_ACTION, test.data.tables.pojos.ContentItemAction.class);
    }

    /**
     * Create a new ContentItemActionDao with an attached configuration
     */
    public ContentItemActionDao(Configuration configuration) {
        super(ContentItemAction.CONTENT_ITEM_ACTION, test.data.tables.pojos.ContentItemAction.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UUID getId(test.data.tables.pojos.ContentItemAction object) {
        return object.getContentItemId();
    }

    /**
     * Fetch records that have <code>content_item_set_id IN (values)</code>
     */
    public List<test.data.tables.pojos.ContentItemAction> fetchByContentItemSetId(UUID... values) {
        return fetch(ContentItemAction.CONTENT_ITEM_ACTION.CONTENT_ITEM_SET_ID, values);
    }

    /**
     * Fetch records that have <code>content_item_id IN (values)</code>
     */
    public List<test.data.tables.pojos.ContentItemAction> fetchByContentItemId(UUID... values) {
        return fetch(ContentItemAction.CONTENT_ITEM_ACTION.CONTENT_ITEM_ID, values);
    }

    /**
     * Fetch a unique record that has <code>content_item_id = value</code>
     */
    public test.data.tables.pojos.ContentItemAction fetchOneByContentItemId(UUID value) {
        return fetchOne(ContentItemAction.CONTENT_ITEM_ACTION.CONTENT_ITEM_ID, value);
    }

    /**
     * Fetch records that have <code>action IN (values)</code>
     */
    public List<test.data.tables.pojos.ContentItemAction> fetchByAction(String... values) {
        return fetch(ContentItemAction.CONTENT_ITEM_ACTION.ACTION, values);
    }

    /**
     * Fetch records that have <code>content IN (values)</code>
     */
    public List<test.data.tables.pojos.ContentItemAction> fetchByContent(Object... values) {
        return fetch(ContentItemAction.CONTENT_ITEM_ACTION.CONTENT, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<test.data.tables.pojos.ContentItemAction> fetchByStatus(String... values) {
        return fetch(ContentItemAction.CONTENT_ITEM_ACTION.STATUS, values);
    }
}
