/*
 * This file is generated by jOOQ.
*/
package test.data.tables.daos;


import java.sql.Timestamp;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import test.data.tables.ContentItemSet;
import test.data.tables.records.ContentItemSetRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContentItemSetDao extends DAOImpl<ContentItemSetRecord, test.data.tables.pojos.ContentItemSet, UUID> {

    /**
     * Create a new ContentItemSetDao without any configuration
     */
    public ContentItemSetDao() {
        super(ContentItemSet.CONTENT_ITEM_SET, test.data.tables.pojos.ContentItemSet.class);
    }

    /**
     * Create a new ContentItemSetDao with an attached configuration
     */
    public ContentItemSetDao(Configuration configuration) {
        super(ContentItemSet.CONTENT_ITEM_SET, test.data.tables.pojos.ContentItemSet.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UUID getId(test.data.tables.pojos.ContentItemSet object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<test.data.tables.pojos.ContentItemSet> fetchById(UUID... values) {
        return fetch(ContentItemSet.CONTENT_ITEM_SET.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public test.data.tables.pojos.ContentItemSet fetchOneById(UUID value) {
        return fetchOne(ContentItemSet.CONTENT_ITEM_SET.ID, value);
    }

    /**
     * Fetch records that have <code>timestamp IN (values)</code>
     */
    public List<test.data.tables.pojos.ContentItemSet> fetchByTimestamp(Timestamp... values) {
        return fetch(ContentItemSet.CONTENT_ITEM_SET.TIMESTAMP, values);
    }

    /**
     * Fetch records that have <code>source IN (values)</code>
     */
    public List<test.data.tables.pojos.ContentItemSet> fetchBySource(String... values) {
        return fetch(ContentItemSet.CONTENT_ITEM_SET.SOURCE, values);
    }
}
