/*
 * This file is generated by jOOQ.
*/
package test.data.tables.records;


import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import test.data.tables.ContentItemStatusReport;
import test.data.tables.interfaces.IContentItemStatusReport;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContentItemStatusReportRecord extends UpdatableRecordImpl<ContentItemStatusReportRecord> implements Record9<UUID, Timestamp, String, String, Integer, Integer, Integer, UUID[], Object[]>, IContentItemStatusReport {

    private static final long serialVersionUID = -1213597921;

    /**
     * Setter for <code>cola.content_item_status_report.id</code>.
     */
    @Override
    public ContentItemStatusReportRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>cola.content_item_status_report.id</code>.
     */
    @Override
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>cola.content_item_status_report.timestamp</code>.
     */
    @Override
    public ContentItemStatusReportRecord setTimestamp(Timestamp value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>cola.content_item_status_report.timestamp</code>.
     */
    @Override
    public Timestamp getTimestamp() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>cola.content_item_status_report.status</code>.
     */
    @Override
    public ContentItemStatusReportRecord setStatus(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>cola.content_item_status_report.status</code>.
     */
    @Override
    public String getStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cola.content_item_status_report.reason</code>.
     */
    @Override
    public ContentItemStatusReportRecord setReason(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>cola.content_item_status_report.reason</code>.
     */
    @Override
    public String getReason() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cola.content_item_status_report.total_items_count</code>.
     */
    @Override
    public ContentItemStatusReportRecord setTotalItemsCount(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>cola.content_item_status_report.total_items_count</code>.
     */
    @Override
    public Integer getTotalItemsCount() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>cola.content_item_status_report.successful_items_count</code>.
     */
    @Override
    public ContentItemStatusReportRecord setSuccessfulItemsCount(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>cola.content_item_status_report.successful_items_count</code>.
     */
    @Override
    public Integer getSuccessfulItemsCount() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>cola.content_item_status_report.failed_items_count</code>.
     */
    @Override
    public ContentItemStatusReportRecord setFailedItemsCount(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>cola.content_item_status_report.failed_items_count</code>.
     */
    @Override
    public Integer getFailedItemsCount() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>cola.content_item_status_report.successful_items</code>.
     */
    @Override
    public ContentItemStatusReportRecord setSuccessfulItems(UUID... value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>cola.content_item_status_report.successful_items</code>.
     */
    @Override
    public UUID[] getSuccessfulItems() {
        return (UUID[]) get(7);
    }

    /**
     * Setter for <code>cola.content_item_status_report.failed_items</code>.
     */
    @Override
    public ContentItemStatusReportRecord setFailedItems(Object... value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>cola.content_item_status_report.failed_items</code>.
     */
    @Override
    public Object[] getFailedItems() {
        return (Object[]) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<UUID, Timestamp, String, String, Integer, Integer, Integer, UUID[], Object[]> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<UUID, Timestamp, String, String, Integer, Integer, Integer, UUID[], Object[]> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return ContentItemStatusReport.CONTENT_ITEM_STATUS_REPORT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return ContentItemStatusReport.CONTENT_ITEM_STATUS_REPORT.TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ContentItemStatusReport.CONTENT_ITEM_STATUS_REPORT.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ContentItemStatusReport.CONTENT_ITEM_STATUS_REPORT.REASON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return ContentItemStatusReport.CONTENT_ITEM_STATUS_REPORT.TOTAL_ITEMS_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return ContentItemStatusReport.CONTENT_ITEM_STATUS_REPORT.SUCCESSFUL_ITEMS_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return ContentItemStatusReport.CONTENT_ITEM_STATUS_REPORT.FAILED_ITEMS_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID[]> field8() {
        return ContentItemStatusReport.CONTENT_ITEM_STATUS_REPORT.SUCCESSFUL_ITEMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object[]> field9() {
        return ContentItemStatusReport.CONTENT_ITEM_STATUS_REPORT.FAILED_ITEMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getTotalItemsCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getSuccessfulItemsCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getFailedItemsCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID[] value8() {
        return getSuccessfulItems();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object[] value9() {
        return getFailedItems();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContentItemStatusReportRecord value1(UUID value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContentItemStatusReportRecord value2(Timestamp value) {
        setTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContentItemStatusReportRecord value3(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContentItemStatusReportRecord value4(String value) {
        setReason(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContentItemStatusReportRecord value5(Integer value) {
        setTotalItemsCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContentItemStatusReportRecord value6(Integer value) {
        setSuccessfulItemsCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContentItemStatusReportRecord value7(Integer value) {
        setFailedItemsCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContentItemStatusReportRecord value8(UUID... value) {
        setSuccessfulItems(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContentItemStatusReportRecord value9(Object... value) {
        setFailedItems(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContentItemStatusReportRecord values(UUID value1, Timestamp value2, String value3, String value4, Integer value5, Integer value6, Integer value7, UUID[] value8, Object[] value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IContentItemStatusReport from) {
        setId(from.getId());
        setTimestamp(from.getTimestamp());
        setStatus(from.getStatus());
        setReason(from.getReason());
        setTotalItemsCount(from.getTotalItemsCount());
        setSuccessfulItemsCount(from.getSuccessfulItemsCount());
        setFailedItemsCount(from.getFailedItemsCount());
        setSuccessfulItems(from.getSuccessfulItems());
        setFailedItems(from.getFailedItems());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IContentItemStatusReport> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContentItemStatusReportRecord
     */
    public ContentItemStatusReportRecord() {
        super(ContentItemStatusReport.CONTENT_ITEM_STATUS_REPORT);
    }

    /**
     * Create a detached, initialised ContentItemStatusReportRecord
     */
    public ContentItemStatusReportRecord(UUID id, Timestamp timestamp, String status, String reason, Integer totalItemsCount, Integer successfulItemsCount, Integer failedItemsCount, UUID[] successfulItems, Object[] failedItems) {
        super(ContentItemStatusReport.CONTENT_ITEM_STATUS_REPORT);

        set(0, id);
        set(1, timestamp);
        set(2, status);
        set(3, reason);
        set(4, totalItemsCount);
        set(5, successfulItemsCount);
        set(6, failedItemsCount);
        set(7, successfulItems);
        set(8, failedItems);
    }
}
