/*
 * This file is generated by jOOQ.
*/
package test.data.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IContentItemSet extends Serializable {

    /**
     * Setter for <code>cola.content_item_set.id</code>.
     */
    public IContentItemSet setId(UUID value);

    /**
     * Getter for <code>cola.content_item_set.id</code>.
     */
    public UUID getId();

    /**
     * Setter for <code>cola.content_item_set.timestamp</code>.
     */
    public IContentItemSet setTimestamp(Timestamp value);

    /**
     * Getter for <code>cola.content_item_set.timestamp</code>.
     */
    public Timestamp getTimestamp();

    /**
     * Setter for <code>cola.content_item_set.source</code>.
     */
    public IContentItemSet setSource(String value);

    /**
     * Getter for <code>cola.content_item_set.source</code>.
     */
    public String getSource();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IContentItemSet
     */
    public void from(test.data.tables.interfaces.IContentItemSet from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IContentItemSet
     */
    public <E extends test.data.tables.interfaces.IContentItemSet> E into(E into);
}
