/*
 * This file is generated by jOOQ.
*/
package test.data.tables.interfaces;


import java.io.Serializable;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IContentItem extends Serializable {

    /**
     * Setter for <code>cola.content_item.id</code>.
     */
    public IContentItem setId(UUID value);

    /**
     * Getter for <code>cola.content_item.id</code>.
     */
    public UUID getId();

    /**
     * Setter for <code>cola.content_item.content_item_set_id</code>.
     */
    public IContentItem setContentItemSetId(UUID value);

    /**
     * Getter for <code>cola.content_item.content_item_set_id</code>.
     */
    public UUID getContentItemSetId();

    /**
     * Setter for <code>cola.content_item.content</code>.
     */
    public IContentItem setContent(Object value);

    /**
     * Getter for <code>cola.content_item.content</code>.
     */
    public Object getContent();

    /**
     * Setter for <code>cola.content_item.original_content</code>.
     */
    public IContentItem setOriginalContent(String value);

    /**
     * Getter for <code>cola.content_item.original_content</code>.
     */
    public String getOriginalContent();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IContentItem
     */
    public void from(test.data.tables.interfaces.IContentItem from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IContentItem
     */
    public <E extends test.data.tables.interfaces.IContentItem> E into(E into);
}
