/*
 * This file is generated by jOOQ.
*/
package test.data.tables.interfaces;


import java.io.Serializable;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IContentItemAction extends Serializable {

    /**
     * Setter for <code>cola.content_item_action.content_item_set_id</code>.
     */
    public IContentItemAction setContentItemSetId(UUID value);

    /**
     * Getter for <code>cola.content_item_action.content_item_set_id</code>.
     */
    public UUID getContentItemSetId();

    /**
     * Setter for <code>cola.content_item_action.content_item_id</code>.
     */
    public IContentItemAction setContentItemId(UUID value);

    /**
     * Getter for <code>cola.content_item_action.content_item_id</code>.
     */
    public UUID getContentItemId();

    /**
     * Setter for <code>cola.content_item_action.action</code>.
     */
    public IContentItemAction setAction(String value);

    /**
     * Getter for <code>cola.content_item_action.action</code>.
     */
    public String getAction();

    /**
     * Setter for <code>cola.content_item_action.content</code>.
     */
    public IContentItemAction setContent(Object value);

    /**
     * Getter for <code>cola.content_item_action.content</code>.
     */
    public Object getContent();

    /**
     * Setter for <code>cola.content_item_action.status</code>.
     */
    public IContentItemAction setStatus(String value);

    /**
     * Getter for <code>cola.content_item_action.status</code>.
     */
    public String getStatus();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IContentItemAction
     */
    public void from(test.data.tables.interfaces.IContentItemAction from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IContentItemAction
     */
    public <E extends test.data.tables.interfaces.IContentItemAction> E into(E into);
}
