/*
 * This file is generated by jOOQ.
*/
package test.data.tables.interfaces;


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IContentItemMatch extends Serializable {

    /**
     * Setter for <code>cola.content_item_match.id</code>.
     */
    public IContentItemMatch setId(Integer value);

    /**
     * Getter for <code>cola.content_item_match.id</code>.
     */
    public Integer getId();

    /**
     * Setter for <code>cola.content_item_match.content_item_set_id</code>.
     */
    public IContentItemMatch setContentItemSetId(UUID value);

    /**
     * Getter for <code>cola.content_item_match.content_item_set_id</code>.
     */
    public UUID getContentItemSetId();

    /**
     * Setter for <code>cola.content_item_match.content_item_id</code>.
     */
    public IContentItemMatch setContentItemId(UUID value);

    /**
     * Getter for <code>cola.content_item_match.content_item_id</code>.
     */
    public UUID getContentItemId();

    /**
     * Setter for <code>cola.content_item_match.source</code>.
     */
    public IContentItemMatch setSource(String value);

    /**
     * Getter for <code>cola.content_item_match.source</code>.
     */
    public String getSource();

    /**
     * Setter for <code>cola.content_item_match.score</code>.
     */
    public IContentItemMatch setScore(BigDecimal value);

    /**
     * Getter for <code>cola.content_item_match.score</code>.
     */
    public BigDecimal getScore();

    /**
     * Setter for <code>cola.content_item_match.match</code>.
     */
    public IContentItemMatch setMatch(Object value);

    /**
     * Getter for <code>cola.content_item_match.match</code>.
     */
    public Object getMatch();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IContentItemMatch
     */
    public void from(test.data.tables.interfaces.IContentItemMatch from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IContentItemMatch
     */
    public <E extends test.data.tables.interfaces.IContentItemMatch> E into(E into);
}
