/*
 * This file is generated by jOOQ.
*/
package test.data;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import test.data.tables.ContentItem;
import test.data.tables.ContentItemAction;
import test.data.tables.ContentItemMatch;
import test.data.tables.ContentItemSet;
import test.data.tables.ContentItemStatusReport;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cola extends SchemaImpl {

    private static final long serialVersionUID = -1948885920;

    /**
     * The reference instance of <code>cola</code>
     */
    public static final Cola COLA = new Cola();

    /**
     * The table <code>cola.content_item</code>.
     */
    public final ContentItem CONTENT_ITEM = test.data.tables.ContentItem.CONTENT_ITEM;

    /**
     * The table <code>cola.content_item_action</code>.
     */
    public final ContentItemAction CONTENT_ITEM_ACTION = test.data.tables.ContentItemAction.CONTENT_ITEM_ACTION;

    /**
     * The table <code>cola.content_item_match</code>.
     */
    public final ContentItemMatch CONTENT_ITEM_MATCH = test.data.tables.ContentItemMatch.CONTENT_ITEM_MATCH;

    /**
     * The table <code>cola.content_item_set</code>.
     */
    public final ContentItemSet CONTENT_ITEM_SET = test.data.tables.ContentItemSet.CONTENT_ITEM_SET;

    /**
     * The table <code>cola.content_item_status_report</code>.
     */
    public final ContentItemStatusReport CONTENT_ITEM_STATUS_REPORT = test.data.tables.ContentItemStatusReport.CONTENT_ITEM_STATUS_REPORT;

    /**
     * No further instances allowed
     */
    private Cola() {
        super("cola", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.CONTENT_ITEM_MATCH_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            ContentItem.CONTENT_ITEM,
            ContentItemAction.CONTENT_ITEM_ACTION,
            ContentItemMatch.CONTENT_ITEM_MATCH,
            ContentItemSet.CONTENT_ITEM_SET,
            ContentItemStatusReport.CONTENT_ITEM_STATUS_REPORT);
    }
}
