/*
 * This file is generated by jOOQ.
*/
package test.data;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import test.data.tables.ContentItem;
import test.data.tables.ContentItemAction;
import test.data.tables.ContentItemMatch;
import test.data.tables.ContentItemSet;
import test.data.tables.ContentItemStatusReport;
import test.data.tables.records.ContentItemActionRecord;
import test.data.tables.records.ContentItemMatchRecord;
import test.data.tables.records.ContentItemRecord;
import test.data.tables.records.ContentItemSetRecord;
import test.data.tables.records.ContentItemStatusReportRecord;


/**
 * A class modelling foreign key relationships between tables of the <code>cola</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ContentItemMatchRecord, Integer> IDENTITY_CONTENT_ITEM_MATCH = Identities0.IDENTITY_CONTENT_ITEM_MATCH;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ContentItemRecord> CONTENT_ITEM_PKEY = UniqueKeys0.CONTENT_ITEM_PKEY;
    public static final UniqueKey<ContentItemActionRecord> CONTENT_ITEM_ACTION_PKEY = UniqueKeys0.CONTENT_ITEM_ACTION_PKEY;
    public static final UniqueKey<ContentItemMatchRecord> CONTENT_ITEM_MATCH_PKEY = UniqueKeys0.CONTENT_ITEM_MATCH_PKEY;
    public static final UniqueKey<ContentItemSetRecord> CONTENT_ITEM_SET_PKEY = UniqueKeys0.CONTENT_ITEM_SET_PKEY;
    public static final UniqueKey<ContentItemStatusReportRecord> CONTENT_ITEM_STATUS_REPORT_PKEY = UniqueKeys0.CONTENT_ITEM_STATUS_REPORT_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ContentItemActionRecord, ContentItemSetRecord> CONTENT_ITEM_ACTION__CONTENT_ITEM_ACTION_CONTENT_ITEM_SET_ID_FKEY = ForeignKeys0.CONTENT_ITEM_ACTION__CONTENT_ITEM_ACTION_CONTENT_ITEM_SET_ID_FKEY;
    public static final ForeignKey<ContentItemActionRecord, ContentItemRecord> CONTENT_ITEM_ACTION__CONTENT_ITEM_ACTION_CONTENT_ITEM_ID_FKEY = ForeignKeys0.CONTENT_ITEM_ACTION__CONTENT_ITEM_ACTION_CONTENT_ITEM_ID_FKEY;
    public static final ForeignKey<ContentItemMatchRecord, ContentItemSetRecord> CONTENT_ITEM_MATCH__CONTENT_ITEM_MATCH_CONTENT_ITEM_SET_ID_FKEY = ForeignKeys0.CONTENT_ITEM_MATCH__CONTENT_ITEM_MATCH_CONTENT_ITEM_SET_ID_FKEY;
    public static final ForeignKey<ContentItemMatchRecord, ContentItemRecord> CONTENT_ITEM_MATCH__CONTENT_ITEM_MATCH_CONTENT_ITEM_ID_FKEY = ForeignKeys0.CONTENT_ITEM_MATCH__CONTENT_ITEM_MATCH_CONTENT_ITEM_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<ContentItemMatchRecord, Integer> IDENTITY_CONTENT_ITEM_MATCH = createIdentity(ContentItemMatch.CONTENT_ITEM_MATCH, ContentItemMatch.CONTENT_ITEM_MATCH.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ContentItemRecord> CONTENT_ITEM_PKEY = createUniqueKey(ContentItem.CONTENT_ITEM, "content_item_pkey", ContentItem.CONTENT_ITEM.ID);
        public static final UniqueKey<ContentItemActionRecord> CONTENT_ITEM_ACTION_PKEY = createUniqueKey(ContentItemAction.CONTENT_ITEM_ACTION, "content_item_action_pkey", ContentItemAction.CONTENT_ITEM_ACTION.CONTENT_ITEM_ID);
        public static final UniqueKey<ContentItemMatchRecord> CONTENT_ITEM_MATCH_PKEY = createUniqueKey(ContentItemMatch.CONTENT_ITEM_MATCH, "content_item_match_pkey", ContentItemMatch.CONTENT_ITEM_MATCH.ID);
        public static final UniqueKey<ContentItemSetRecord> CONTENT_ITEM_SET_PKEY = createUniqueKey(ContentItemSet.CONTENT_ITEM_SET, "content_item_set_pkey", ContentItemSet.CONTENT_ITEM_SET.ID);
        public static final UniqueKey<ContentItemStatusReportRecord> CONTENT_ITEM_STATUS_REPORT_PKEY = createUniqueKey(ContentItemStatusReport.CONTENT_ITEM_STATUS_REPORT, "content_item_status_report_pkey", ContentItemStatusReport.CONTENT_ITEM_STATUS_REPORT.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<ContentItemActionRecord, ContentItemSetRecord> CONTENT_ITEM_ACTION__CONTENT_ITEM_ACTION_CONTENT_ITEM_SET_ID_FKEY = createForeignKey(test.data.Keys.CONTENT_ITEM_SET_PKEY, ContentItemAction.CONTENT_ITEM_ACTION, "content_item_action__content_item_action_content_item_set_id_fkey", ContentItemAction.CONTENT_ITEM_ACTION.CONTENT_ITEM_SET_ID);
        public static final ForeignKey<ContentItemActionRecord, ContentItemRecord> CONTENT_ITEM_ACTION__CONTENT_ITEM_ACTION_CONTENT_ITEM_ID_FKEY = createForeignKey(test.data.Keys.CONTENT_ITEM_PKEY, ContentItemAction.CONTENT_ITEM_ACTION, "content_item_action__content_item_action_content_item_id_fkey", ContentItemAction.CONTENT_ITEM_ACTION.CONTENT_ITEM_ID);
        public static final ForeignKey<ContentItemMatchRecord, ContentItemSetRecord> CONTENT_ITEM_MATCH__CONTENT_ITEM_MATCH_CONTENT_ITEM_SET_ID_FKEY = createForeignKey(test.data.Keys.CONTENT_ITEM_SET_PKEY, ContentItemMatch.CONTENT_ITEM_MATCH, "content_item_match__content_item_match_content_item_set_id_fkey", ContentItemMatch.CONTENT_ITEM_MATCH.CONTENT_ITEM_SET_ID);
        public static final ForeignKey<ContentItemMatchRecord, ContentItemRecord> CONTENT_ITEM_MATCH__CONTENT_ITEM_MATCH_CONTENT_ITEM_ID_FKEY = createForeignKey(test.data.Keys.CONTENT_ITEM_PKEY, ContentItemMatch.CONTENT_ITEM_MATCH, "content_item_match__content_item_match_content_item_id_fkey", ContentItemMatch.CONTENT_ITEM_MATCH.CONTENT_ITEM_ID);
    }
}
