/*
 * This file is generated by jOOQ.
*/
package test.data;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in cola
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>cola.content_item_match_id_seq</code>
     */
    public static final Sequence<Long> CONTENT_ITEM_MATCH_ID_SEQ = new SequenceImpl<Long>("content_item_match_id_seq", Cola.COLA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
