/*
 * This file is generated by jOOQ.
*/
package test.data.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import test.data.Cola;
import test.data.Keys;
import test.data.tables.records.ContentItemActionRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContentItemAction extends TableImpl<ContentItemActionRecord> {

    private static final long serialVersionUID = 486366198;

    /**
     * The reference instance of <code>cola.content_item_action</code>
     */
    public static final ContentItemAction CONTENT_ITEM_ACTION = new ContentItemAction();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContentItemActionRecord> getRecordType() {
        return ContentItemActionRecord.class;
    }

    /**
     * The column <code>cola.content_item_action.content_item_set_id</code>.
     */
    public final TableField<ContentItemActionRecord, UUID> CONTENT_ITEM_SET_ID = createField("content_item_set_id", org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * The column <code>cola.content_item_action.content_item_id</code>.
     */
    public final TableField<ContentItemActionRecord, UUID> CONTENT_ITEM_ID = createField("content_item_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>cola.content_item_action.action</code>.
     */
    public final TableField<ContentItemActionRecord, String> ACTION = createField("action", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>cola.content_item_action.content</code>.
     */
    public final TableField<ContentItemActionRecord, Object> CONTENT = createField("content", org.jooq.impl.DefaultDataType.getDefaultDataType("jsonb"), this, "");

    /**
     * The column <code>cola.content_item_action.status</code>.
     */
    public final TableField<ContentItemActionRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>cola.content_item_action</code> table reference
     */
    public ContentItemAction() {
        this("content_item_action", null);
    }

    /**
     * Create an aliased <code>cola.content_item_action</code> table reference
     */
    public ContentItemAction(String alias) {
        this(alias, CONTENT_ITEM_ACTION);
    }

    private ContentItemAction(String alias, Table<ContentItemActionRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContentItemAction(String alias, Table<ContentItemActionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Cola.COLA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ContentItemActionRecord> getPrimaryKey() {
        return Keys.CONTENT_ITEM_ACTION_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ContentItemActionRecord>> getKeys() {
        return Arrays.<UniqueKey<ContentItemActionRecord>>asList(Keys.CONTENT_ITEM_ACTION_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ContentItemActionRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ContentItemActionRecord, ?>>asList(Keys.CONTENT_ITEM_ACTION__CONTENT_ITEM_ACTION_CONTENT_ITEM_SET_ID_FKEY, Keys.CONTENT_ITEM_ACTION__CONTENT_ITEM_ACTION_CONTENT_ITEM_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContentItemAction as(String alias) {
        return new ContentItemAction(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContentItemAction rename(String name) {
        return new ContentItemAction(name, null);
    }
}
