/*
 * This file is generated by jOOQ.
*/
package test.data.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import test.data.Cola;
import test.data.Keys;
import test.data.tables.records.ContentItemSetRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContentItemSet extends TableImpl<ContentItemSetRecord> {

    private static final long serialVersionUID = 331223778;

    /**
     * The reference instance of <code>cola.content_item_set</code>
     */
    public static final ContentItemSet CONTENT_ITEM_SET = new ContentItemSet();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContentItemSetRecord> getRecordType() {
        return ContentItemSetRecord.class;
    }

    /**
     * The column <code>cola.content_item_set.id</code>.
     */
    public final TableField<ContentItemSetRecord, UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>cola.content_item_set.timestamp</code>.
     */
    public final TableField<ContentItemSetRecord, Timestamp> TIMESTAMP = createField("timestamp", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>cola.content_item_set.source</code>.
     */
    public final TableField<ContentItemSetRecord, String> SOURCE = createField("source", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>cola.content_item_set</code> table reference
     */
    public ContentItemSet() {
        this("content_item_set", null);
    }

    /**
     * Create an aliased <code>cola.content_item_set</code> table reference
     */
    public ContentItemSet(String alias) {
        this(alias, CONTENT_ITEM_SET);
    }

    private ContentItemSet(String alias, Table<ContentItemSetRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContentItemSet(String alias, Table<ContentItemSetRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Cola.COLA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ContentItemSetRecord> getPrimaryKey() {
        return Keys.CONTENT_ITEM_SET_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ContentItemSetRecord>> getKeys() {
        return Arrays.<UniqueKey<ContentItemSetRecord>>asList(Keys.CONTENT_ITEM_SET_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContentItemSet as(String alias) {
        return new ContentItemSet(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContentItemSet rename(String name) {
        return new ContentItemSet(name, null);
    }
}
