/*
 * This file is generated by jOOQ.
*/
package test.data.tables.pojos;


import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;

import test.data.tables.interfaces.IContentItemSet;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContentItemSet implements IContentItemSet {

    private static final long serialVersionUID = 1433405815;

    private UUID      id;
    private Timestamp timestamp;
    private String    source;

    public ContentItemSet() {}

    public ContentItemSet(ContentItemSet value) {
        this.id = value.id;
        this.timestamp = value.timestamp;
        this.source = value.source;
    }

    public ContentItemSet(
        UUID      id,
        Timestamp timestamp,
        String    source
    ) {
        this.id = id;
        this.timestamp = timestamp;
        this.source = source;
    }

    @Override
    public UUID getId() {
        return this.id;
    }

    @Override
    public ContentItemSet setId(UUID id) {
        this.id = id;
        return this;
    }

    @Override
    public Timestamp getTimestamp() {
        return this.timestamp;
    }

    @Override
    public ContentItemSet setTimestamp(Timestamp timestamp) {
        this.timestamp = timestamp;
        return this;
    }

    @Override
    public String getSource() {
        return this.source;
    }

    @Override
    public ContentItemSet setSource(String source) {
        this.source = source;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ContentItemSet (");

        sb.append(id);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(source);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IContentItemSet from) {
        setId(from.getId());
        setTimestamp(from.getTimestamp());
        setSource(from.getSource());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IContentItemSet> E into(E into) {
        into.from(this);
        return into;
    }
}
