/*
 * This file is generated by jOOQ.
*/
package test.data.tables.pojos;


import java.util.UUID;

import javax.annotation.Generated;

import test.data.tables.interfaces.IContentItemAction;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContentItemAction implements IContentItemAction {

    private static final long serialVersionUID = 488327368;

    private UUID   contentItemSetId;
    private UUID   contentItemId;
    private String action;
    private Object content;
    private String status;

    public ContentItemAction() {}

    public ContentItemAction(ContentItemAction value) {
        this.contentItemSetId = value.contentItemSetId;
        this.contentItemId = value.contentItemId;
        this.action = value.action;
        this.content = value.content;
        this.status = value.status;
    }

    public ContentItemAction(
        UUID   contentItemSetId,
        UUID   contentItemId,
        String action,
        Object content,
        String status
    ) {
        this.contentItemSetId = contentItemSetId;
        this.contentItemId = contentItemId;
        this.action = action;
        this.content = content;
        this.status = status;
    }

    @Override
    public UUID getContentItemSetId() {
        return this.contentItemSetId;
    }

    @Override
    public ContentItemAction setContentItemSetId(UUID contentItemSetId) {
        this.contentItemSetId = contentItemSetId;
        return this;
    }

    @Override
    public UUID getContentItemId() {
        return this.contentItemId;
    }

    @Override
    public ContentItemAction setContentItemId(UUID contentItemId) {
        this.contentItemId = contentItemId;
        return this;
    }

    @Override
    public String getAction() {
        return this.action;
    }

    @Override
    public ContentItemAction setAction(String action) {
        this.action = action;
        return this;
    }

    @Override
    public Object getContent() {
        return this.content;
    }

    @Override
    public ContentItemAction setContent(Object content) {
        this.content = content;
        return this;
    }

    @Override
    public String getStatus() {
        return this.status;
    }

    @Override
    public ContentItemAction setStatus(String status) {
        this.status = status;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ContentItemAction (");

        sb.append(contentItemSetId);
        sb.append(", ").append(contentItemId);
        sb.append(", ").append(action);
        sb.append(", ").append(content);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IContentItemAction from) {
        setContentItemSetId(from.getContentItemSetId());
        setContentItemId(from.getContentItemId());
        setAction(from.getAction());
        setContent(from.getContent());
        setStatus(from.getStatus());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IContentItemAction> E into(E into) {
        into.from(this);
        return into;
    }
}
