/*
 * This file is generated by jOOQ.
*/
package test.data.tables.pojos;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.UUID;

import javax.annotation.Generated;

import test.data.tables.interfaces.IContentItemStatusReport;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContentItemStatusReport implements IContentItemStatusReport {

    private static final long serialVersionUID = -1360602727;

    private UUID      id;
    private Timestamp timestamp;
    private String    status;
    private String    reason;
    private Integer   totalItemsCount;
    private Integer   successfulItemsCount;
    private Integer   failedItemsCount;
    private UUID[]    successfulItems;
    private Object[]  failedItems;

    public ContentItemStatusReport() {}

    public ContentItemStatusReport(ContentItemStatusReport value) {
        this.id = value.id;
        this.timestamp = value.timestamp;
        this.status = value.status;
        this.reason = value.reason;
        this.totalItemsCount = value.totalItemsCount;
        this.successfulItemsCount = value.successfulItemsCount;
        this.failedItemsCount = value.failedItemsCount;
        this.successfulItems = value.successfulItems;
        this.failedItems = value.failedItems;
    }

    public ContentItemStatusReport(
        UUID      id,
        Timestamp timestamp,
        String    status,
        String    reason,
        Integer   totalItemsCount,
        Integer   successfulItemsCount,
        Integer   failedItemsCount,
        UUID[]    successfulItems,
        Object[]  failedItems
    ) {
        this.id = id;
        this.timestamp = timestamp;
        this.status = status;
        this.reason = reason;
        this.totalItemsCount = totalItemsCount;
        this.successfulItemsCount = successfulItemsCount;
        this.failedItemsCount = failedItemsCount;
        this.successfulItems = successfulItems;
        this.failedItems = failedItems;
    }

    @Override
    public UUID getId() {
        return this.id;
    }

    @Override
    public ContentItemStatusReport setId(UUID id) {
        this.id = id;
        return this;
    }

    @Override
    public Timestamp getTimestamp() {
        return this.timestamp;
    }

    @Override
    public ContentItemStatusReport setTimestamp(Timestamp timestamp) {
        this.timestamp = timestamp;
        return this;
    }

    @Override
    public String getStatus() {
        return this.status;
    }

    @Override
    public ContentItemStatusReport setStatus(String status) {
        this.status = status;
        return this;
    }

    @Override
    public String getReason() {
        return this.reason;
    }

    @Override
    public ContentItemStatusReport setReason(String reason) {
        this.reason = reason;
        return this;
    }

    @Override
    public Integer getTotalItemsCount() {
        return this.totalItemsCount;
    }

    @Override
    public ContentItemStatusReport setTotalItemsCount(Integer totalItemsCount) {
        this.totalItemsCount = totalItemsCount;
        return this;
    }

    @Override
    public Integer getSuccessfulItemsCount() {
        return this.successfulItemsCount;
    }

    @Override
    public ContentItemStatusReport setSuccessfulItemsCount(Integer successfulItemsCount) {
        this.successfulItemsCount = successfulItemsCount;
        return this;
    }

    @Override
    public Integer getFailedItemsCount() {
        return this.failedItemsCount;
    }

    @Override
    public ContentItemStatusReport setFailedItemsCount(Integer failedItemsCount) {
        this.failedItemsCount = failedItemsCount;
        return this;
    }

    @Override
    public UUID[] getSuccessfulItems() {
        return this.successfulItems;
    }

    @Override
    public ContentItemStatusReport setSuccessfulItems(UUID... successfulItems) {
        this.successfulItems = successfulItems;
        return this;
    }

    @Override
    public Object[] getFailedItems() {
        return this.failedItems;
    }

    @Override
    public ContentItemStatusReport setFailedItems(Object... failedItems) {
        this.failedItems = failedItems;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ContentItemStatusReport (");

        sb.append(id);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(status);
        sb.append(", ").append(reason);
        sb.append(", ").append(totalItemsCount);
        sb.append(", ").append(successfulItemsCount);
        sb.append(", ").append(failedItemsCount);
        sb.append(", ").append(Arrays.toString(successfulItems));
        sb.append(", ").append(Arrays.toString(failedItems));

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IContentItemStatusReport from) {
        setId(from.getId());
        setTimestamp(from.getTimestamp());
        setStatus(from.getStatus());
        setReason(from.getReason());
        setTotalItemsCount(from.getTotalItemsCount());
        setSuccessfulItemsCount(from.getSuccessfulItemsCount());
        setFailedItemsCount(from.getFailedItemsCount());
        setSuccessfulItems(from.getSuccessfulItems());
        setFailedItems(from.getFailedItems());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IContentItemStatusReport> E into(E into) {
        into.from(this);
        return into;
    }
}
