/*
 * This file is generated by jOOQ.
*/
package test.data.tables.pojos;


import java.math.BigDecimal;
import java.util.UUID;

import javax.annotation.Generated;

import test.data.tables.interfaces.IContentItemMatch;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContentItemMatch implements IContentItemMatch {

    private static final long serialVersionUID = 1839463205;

    private Integer    id;
    private UUID       contentItemSetId;
    private UUID       contentItemId;
    private String     source;
    private BigDecimal score;
    private Object     match;

    public ContentItemMatch() {}

    public ContentItemMatch(ContentItemMatch value) {
        this.id = value.id;
        this.contentItemSetId = value.contentItemSetId;
        this.contentItemId = value.contentItemId;
        this.source = value.source;
        this.score = value.score;
        this.match = value.match;
    }

    public ContentItemMatch(
        Integer    id,
        UUID       contentItemSetId,
        UUID       contentItemId,
        String     source,
        BigDecimal score,
        Object     match
    ) {
        this.id = id;
        this.contentItemSetId = contentItemSetId;
        this.contentItemId = contentItemId;
        this.source = source;
        this.score = score;
        this.match = match;
    }

    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public ContentItemMatch setId(Integer id) {
        this.id = id;
        return this;
    }

    @Override
    public UUID getContentItemSetId() {
        return this.contentItemSetId;
    }

    @Override
    public ContentItemMatch setContentItemSetId(UUID contentItemSetId) {
        this.contentItemSetId = contentItemSetId;
        return this;
    }

    @Override
    public UUID getContentItemId() {
        return this.contentItemId;
    }

    @Override
    public ContentItemMatch setContentItemId(UUID contentItemId) {
        this.contentItemId = contentItemId;
        return this;
    }

    @Override
    public String getSource() {
        return this.source;
    }

    @Override
    public ContentItemMatch setSource(String source) {
        this.source = source;
        return this;
    }

    @Override
    public BigDecimal getScore() {
        return this.score;
    }

    @Override
    public ContentItemMatch setScore(BigDecimal score) {
        this.score = score;
        return this;
    }

    @Override
    public Object getMatch() {
        return this.match;
    }

    @Override
    public ContentItemMatch setMatch(Object match) {
        this.match = match;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ContentItemMatch (");

        sb.append(id);
        sb.append(", ").append(contentItemSetId);
        sb.append(", ").append(contentItemId);
        sb.append(", ").append(source);
        sb.append(", ").append(score);
        sb.append(", ").append(match);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IContentItemMatch from) {
        setId(from.getId());
        setContentItemSetId(from.getContentItemSetId());
        setContentItemId(from.getContentItemId());
        setSource(from.getSource());
        setScore(from.getScore());
        setMatch(from.getMatch());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IContentItemMatch> E into(E into) {
        into.from(this);
        return into;
    }
}
